apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  serviceName: "prometheus-alertmanager"
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:v0.24.0
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-storage
          mountPath: /alertmanager
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi  
      storageClassName: gp2-immediate 
